//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monografia_Profesor
    {
        public int IdMonografia_Profesor { get; set; }
        public int Idmonografia { get; set; }
        public int Idprofesor { get; set; }
        public string Rol { get; set; }
    
        public virtual Monografia Monografia { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
